### ISSUE TITLE
sidenav css outline issue

### ISSUE THREAD

**Issue by t2ca** [system-ui/theme-ui#620] opened 2020-01-28 01:41 UTC
There appears to be a CSS bug in Safari that shows an outline on the top link "Getting Started"

Steps to reproduce:
1. Open Safari on desktop
2. Make window smaller until menu shows up
3. Click on hamburger menu
4. The top link show an outline

**Comment by lachlanjc** [comment] 2020-01-28 02:55
Not sure what to do here…isn't that expected behavior? The top link is outlined, when you Opt-Tab, the outline goes to the next link. What do you think it should do instead?

**Comment by t2ca** [comment] 2020-01-28 05:30
In my experience the outline, which is a purple border, stays on the top link "Getting Started" even after clicking on different menu links. Im not getting the same result in chrome.

**Comment by jxnblk** [comment] 2020-04-07 19:57
Closing this because this is the intended behavior: opening the menu focuses the first element in the navigation

**Closed by jxnblk** 2020-04-07 19:57 UTC
