### ISSUE TITLE
Separate scrolling of sidebar & main content on the website

### ISSUE THREAD

**Issue by deadcoder0904** [system-ui/theme-ui#1068] opened 2020-07-16 06:45 UTC
**Is your feature request related to a problem? Please describe.**
Scroll sidebar separately than the main content so it doesn't jump up when I have `Components` & `Packages` open & I click on `Packages > @theme-ui/core`. Because then I have to scroll all the way to the bottom to get to another package like `Packages > @theme-ui/components` or anything else.

**Describe the solution you'd like**
I want the sidebar to be like https://tailwindcss.com/docs/ where the sidebar position remains the same even if the main content changes.

**Additional context**
Theme UI looks like (~5MB):

![theme-ui](https://user-images.githubusercontent.com/16436270/87635638-05b73480-c75d-11ea-8ce2-c6e674776ac3.gif)

I want it to be like Tailwind (~3MB):

![tailwind](https://user-images.githubusercontent.com/16436270/87636114-d523ca80-c75d-11ea-94d5-76561047411d.gif)

**Comment by lachlanjc** [comment] 2020-07-16 14:24
Looks like a duplicate of #598?

**Comment by lachlanjc** [comment] 2020-11-12 20:15
@hasparus close as duplicate?

**Closed** 2020-11-14 07:48 UTC
