### ISSUE TITLE
Failed to compile due to wrong import

### ISSUE THREAD

**Issue by FilipVOanca** [system-ui/theme-ui#1377] opened 2020-12-17 14:04 UTC
**Describe the bug**
I am using the last version of theme-ui and when I "npm start" I receive a compile error

**To Reproduce**
Just npm start and you will receive this error
I think the pictures says it all.
![image](https://user-images.githubusercontent.com/36967831/102497582-7b635b80-4081-11eb-9f62-61af8a6433ef.png)

**Comment by lachlanjc** [comment] 2020-12-17 14:40
Hey! Can you give more details? Your Theme UI version, React version, framework & version, Node version, your usage of Theme UI, etc? Otherwise we can't reproduce.

**Comment by AndreiLucaci** [comment] 2020-12-17 17:33
I have the same issue, and it appeared after your upgrade (3 hours ago). 

- theme-ui version: latest
- react version: `^16.13.1`
- node: `v12.18.3`

It's simple to reproduce the issue. Using `theme-ui`, running the project yields the error. For me, the index is giving that error:

![image](https://user-images.githubusercontent.com/1398757/102522261-b88a1680-409e-11eb-9bdf-57c1de02cfc2.png)

**Comment by hasparus** [comment] 2020-12-21 09:51
Hello @Pypp, and @AndreiLucaci. Thanks for the issue!

This was an unintended breaking change for TypeScript users.

Let me explain what happened and how to fix it. This is a TypeScript Error number 1128.

You can see that there's a "Declaration or statement expected", so there's some syntax (export type) that didn't parse.
Type-only exports were added in February, in TypeScript 3.8. What's your TypeScript version?

If you can't update your TypeScript version to 3.8 or higher, downgrading Theme UI to 0.3.1 should help.

**Comment by hasparus** [comment] 2020-12-21 10:41
@AndreiLucaci, @Pypp I just released Theme UI 0.3.5 with a fix for this.

`@types/theme-ui` from DefinitelyTyped is compatible with Theme UI 0.3 and old TypeScript, so you should be okay after updating `0.3.5`.

Let me know if it went, and we'll close the issue.

**Closed as completed** 2021-06-10 20:27 UTC
Labels: bug, types, internal
