### ISSUE TITLE
Attempted import error: 'Themed' is not exported from '@theme-ui/mdx'.

### ISSUE THREAD

**Issue by rafinskipg** [system-ui/theme-ui#1846] opened 2021-06-28 17:50 UTC
**Describe the bug**
Updated theme ui and deps to 0.10.0

**To Reproduce**
Try to launch app

Not happens on 0.9.2

```
Attempted import error: 'Themed' is not exported from '@theme-ui/mdx'.
```

**Comment by hasparus** [comment] 2021-06-28 20:11
Hey @rafinskipg! Thanks for the issue.

Do you have any reproduction?

https://codesandbox.io/s/vigilant-aryabhata-7m7pp?file=/src/App.js

I just made a qucik CodeSandbox to check this, and it seems that Themed can be properly imported in a fresh project, so it might be something with your setup.

Could I see your lockfile? (package-lock.json or yarn.lock)?

**Comment by rafinskipg** [comment] 2021-07-01 10:39
Hello, note that i'm not importing any "themed" anywhere, but the error happens somewhere inside the dependencies. 

I will try again and send more info

**Comment by hasparus** [comment] 2021-07-01 12:27
> Hello, note that i'm not importing any "themed" anywhere, but the error happens somewhere inside the dependencies.

There might be an old version of `@theme-ui/mdx` in your `node_modules`. The root package `theme-ui` is reexporting `Themed` from it.

```tsx
export { Themed, Styled, components } from '@theme-ui/mdx'
```

**Comment by lachlanjc** [comment] 2021-07-09 16:54
I'd try `npm ci` to reinstall?

**Comment by hasparus** [comment] 2021-09-08 16:44
Closing because we can't reproduce.

**Closed as completed by hasparus** 2021-09-08 16:44 UTC
