### ISSUE TITLE
Next.js not applying styles to MDX components

### ISSUE THREAD

**Issue by jonashaefele** [system-ui/theme-ui#1130] opened 2020-08-14 18:00 UTC
**Describe the bug**
I ran into the same issue described [here](https://github.com/vercel/next.js/issues/13047) and [here](https://github.com/hashicorp/next-mdx-enhanced/issues/53)

When rendering MDX pages in Next.js, the styles defined in theme.js don't get applied.

The styles get applied perfectly well when using `Styled.h1` and its sibling components in a JSX file, but the MDX parser seems to render plain HTML tags without the classes needed to apply the styles defined the `theme.js`

**To Reproduce**

The issue is present in the [next example](https://github.com/system-ui/theme-ui/tree/master/examples/next) in this repo. Run the example and you'll see that only the root styles are applied, but the MDX components are rendered plain, without styles.

The H1 should be `color: 'primary'` (#07c) but gets rendered with the black (#000) inherited from the root styles applied to the body.

Change the first few lines in `index.mdx` to make it easier to see:

```
import { Styled } from 'theme-ui'

# MD H1

<Styled.h1>Styled H1</Styled.h1>
```

**Expected behavior**

I'd expect MDX files to render the MD components with all the ThemeUI styles defined in the `styles` object of `theme.js` or in other words to `# Title` should render identically to `<Styled.h1>Title</Styled.h1>`, etc.

**Screenshots**

<img width="1180" alt="Screen Shot 2020-08-14 at 18 45 14" src="https://user-images.githubusercontent.com/1152888/90277916-64f08d80-de5e-11ea-94ab-ab0e8ab378a5.png">
<img width="1182" alt="Screen Shot 2020-08-14 at 18 45 23" src="https://user-images.githubusercontent.com/1152888/90277923-6752e780-de5e-11ea-919f-c6b7e74492f2.png">

**Additional context**
It looks like it might be a [next.js bug](https://github.com/hashicorp/next-mdx-enhanced/issues/53), but all the issues related to it have been closed.

I tried to debug it for two days now. I changed the versions for `next` and `@next/mdx` to
- 9.3.3
- 9.3.6
- 9.5.1
- 9.5.2

All of which were suggested should work at some point in issue comments, but none of them seem to work in the next example or my project (which is more complex, so I tried to  isolate the issue).

I appreciate this might not be a theme-ui issue, but thought maybe someone has already solved it.:

Edit: I also tried to swap `@next/mdx` for https://github.com/hashicorp/next-mdx-enhanced (latest) but that didn't help either.

**Comment by lachlanjc** [comment] 2020-08-14 23:11
Yup, can confirm. This has been the case for at least a year in every version & configuration I've tried of all 3 tools.

**Comment by matthewsimo** [comment] 2020-08-23 18:40
This worked for me too - handy tip, thanks for sharing @cwgw.

**Comment by jonashaefele** [comment] 2020-08-24 12:05
Thanks @jxnblk @cwgw that was exactly the problem.

**Comment by pixelmord** [comment] 2020-08-25 15:22
Resolving to the version of `@mdx-js/react` that is used by the mdx loader in my nextjs project (next-mdx-enhanced) also solved the issue for me: THX @cwgw and @jxnblk 
@jxnblk maybe upgrading theme-ui deps to `@mdx-js/react@1.6.16` could prevent others from having that issue...

**Comment by atanasster** [comment] 2020-11-03 04:38
@hasparus - are you working on this issue to try to close it?

I also have a commit upgrading the packages https://github.com/atanasster/theme-ui/commit/29cbc1706e92a135feecb7455c3b79dba2138e30 , however I was not able to reproduce the issue myself. 
lmk

**Comment by lachlanjc** [comment] 2021-12-30 06:33
Now that v0.13 of Theme UI requires installing `@mdx-js/react` yourself, I’m not seeing this issue anymore! Tested with https://github.com/lachlanjc/next-theme-starter (which I haven’t pushed a v0.13 update to yet). Please flag if it returns!

**Closed by lachlanjc** 2021-12-30 06:33 UTC
Labels: bug
