### ISSUE TITLE
sx prop outputs invalid css property value if missing from theme

### ISSUE THREAD

**Issue by devdigital** [system-ui/theme-ui#520] opened 2019-12-19 09:49 UTC
It appears if a theme is missing a property, then the `sx` prop will output the raw property name as the css property value. Is this expected behaviour?

E.g.

```jsx
<h1
  sx={{
    color: 'accent',
  }}>
   Hello
</h1>
```

If the theme does not have an `accent` color, then the CSS output is invalid:

```
color: accent
```

I would expect no rule to be outputted in this case?

**Comment by devdigital** [comment] 2019-12-19 10:21
Just seen in the [docs](https://theme-ui.com/api/#css) that this is expected behaviour. Perhaps would be nice to opt in to a 'no output' behaviour instead.

**Comment by jxnblk** [comment] 2019-12-19 16:04
We've discussed adding development-only warnings for using values that are not available in the theme, but this is the expected behavior in the current implementation

**Comment by devdigital** [comment] 2019-12-19 16:43
I think warnings would be a useful, at the moment components could have an implicit dependency on certain theme properties and consumers may inadvertently end up with invalid CSS. The only way for a consumer to know what is required is by inspecting the component code. 

I think the Theme UI component development experience could be improved by providing a simple API for a fallback value if the theme value is not present.

**Comment by jxnblk** [comment] 2020-01-02 19:28
Closing this for now, since this is the current behavior and changing this would be a much larger change to the API

**Closed by jxnblk** 2020-01-02 19:28 UTC
