### ISSUE TITLE
UI Component Shadowing

### ISSUE THREAD

**Issue by marcwiest** [system-ui/theme-ui#781] opened 2020-03-18 07:17 UTC
Howdy, I've been busy all morning long trying to shadow the AspectRatio UI component as I need to add `width:100%` to the wrapping element.

To not make this more complex than necessary I'm now going to replace this component with a component of my own. However, since I'm using the theme-ui Gatsby theme `gatsby-plugin-theme-ui`, shouldn't I be able to also shadow theme-ui's UI components? 

I'm not sure I'm missing something as I'm still a bit new to Gatsby, but I tried a few different approaches and couldn't get the component shadowed. 
Thanks

**Comment by jxnblk** [comment] 2020-03-19 18:55
You shouldn't need to use Gatsby's shadowing API for components unless you're using a theme (though technically the `gatsby-plugin-theme-ui` uses shadowing for configuration). You can use the `sx` prop or a variant on the AspectRatio component, if you need to adjust the styles

**Comment by marcwiest** [comment] 2020-03-19 20:36
Yes, I'm aware that I can modify the UI components via the `sx` prop. The thing is though, the AspectRatio component does not offer a way to address the wrapping element, only the [inner element](https://github.com/system-ui/theme-ui/blob/master/packages/components/src/AspectRatio.js#L20) that wraps the `{children}`.

**Comment by lachlanjc** [comment] 2020-12-06 19:38
Closing as a duplicate of #706—we definitely want to put `sx` on the container tags of components

**Closed by lachlanjc** 2020-12-06 19:38 UTC
Labels: enhancement
