### ISSUE TITLE
CSS prop unable to override responsive theme config

### ISSUE THREAD

**Issue by sanandnarayan** [system-ui/theme-ui#43] opened 2019-06-04 00:20 UTC
When the developer sets the value only for the first viewport, The CSS props function is unable to override all viewport values of the theme config . 

```Javascript
//theme.js
const breakpoints = ["52em"];
const styles = {
  h1: {
    color: ["red", "blue"]
  }
};
```

```JSX    
<Styled.h1 css={css({ color: ["rebeccapurple" ]})}>
  {props.children}
</Styled.h1>
```
I expected this to override the the larger viewports as well. But i had to explicitly set the value for all viewports.
```JSX    
<Styled.h1 css={css({ color: ["rebeccapurple", 'rebeccapurple'] })}>
  {props.children}
</Styled.h1>
```
I have reproduced the issue in this [codesanbox](https://codesandbox.io/s/theme-ui-css-discussion-oldyz).  you can reproduce the issue by resizing

Is this the intended behaviour? If not, can we filter the props and merge in jsx function/pragma?

**Comment by sanandnarayan** [comment] 2019-06-04 05:53
@jxnblk can i take a stab at fixing this?

**Comment by jxnblk** [comment] 2019-06-04 16:40
@sanandnarayan absolutely! Sorry I missed this last night, but no need to ask permission, especially if it's something that has a `bug` label. TBH, I'm not sure what the best way to fix this is since it's sort of happening because of CSS specificity, but it's not the intended behavior

**Comment by sanandnarayan** [comment] 2019-06-05 04:40
hmm right. let me think through this a little more.

**Comment by jxnblk** [comment] 2019-09-17 16:10
@sanandnarayan if you're still interested in taking a stab at this, feel free to open a PR, but I'm going to close this issue for now and maybe revisit it in `@styled-system/css` at some point in the future

**Closed by jxnblk** 2019-09-17 16:10 UTC
Labels: bug, help wanted
