### ISSUE TITLE
Theme-ui + latest Gatsby seem to have issues

### ISSUE THREAD

**Issue by gvocale** [system-ui/theme-ui#1149] opened 2020-08-22 04:29 UTC
**Describe the bug**
When I update all packages to latest into `gatsby-starter-theme-ui`, Theme Ui is not working correctly anymore.

**To Reproduce**
1. Create a new gatsby project from `gatsby-starter-theme-ui`
```sh
gatsby new test https://github.com/KyleAMathews/gatsby-starter-theme-ui
```
2. Start site
```sh
cd test
gatsby develop
```
3. All works good
4. Now update all packages
```
yarn upgrade-interactive --latest
```
5. Start gatsby again
```
gatsby develop
```
6. Now it doesn't work anymore. The gatsby site works, but theme-ui styles don't get applied anymore.

**Before**
<img width="729" alt="Screen Shot 2020-08-21 at 11 25 06 PM" src="https://user-images.githubusercontent.com/1319291/90948612-1b77e380-e406-11ea-87e5-19a9587cc57e.png">

<img width="351" alt="Screen Shot 2020-08-21 at 11 28 13 PM" src="https://user-images.githubusercontent.com/1319291/90948614-1d41a700-e406-11ea-9ea0-923855c796d7.png">

**After**
<img width="846" alt="Screen Shot 2020-08-21 at 11 28 26 PM" src="https://user-images.githubusercontent.com/1319291/90948611-174bc600-e406-11ea-9c0c-4be3a7e9e5d4.png">

<img width="328" alt="Screen Shot 2020-08-21 at 11 28 35 PM" src="https://user-images.githubusercontent.com/1319291/90948610-1450d580-e406-11ea-94dc-ecf31156763c.png">

**Packages installed**
```json
{
  "name": "gatsby-starter-default-theme-ui",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby & Theme UI",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "@emotion/core": "^10.0.35",
    "@mdx-js/react": "^1.6.16",
    "@theme-ui/components": "^0.3.1",
    "@theme-ui/presets": "^0.3.0",
    "gatsby": "^2.24.47",
    "gatsby-image": "^2.4.16",
    "gatsby-plugin-manifest": "^2.4.23",
    "gatsby-plugin-offline": "^3.2.23",
    "gatsby-plugin-react-helmet": "^3.3.10",
    "gatsby-plugin-sharp": "^2.6.27",
    "gatsby-plugin-theme-ui": "^0.3.0",
    "gatsby-source-filesystem": "^2.3.24",
    "gatsby-theme-style-guide": "^0.3.1",
    "gatsby-transformer-sharp": "^2.5.13",
    "normalize.css": "^8.0.1",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-helmet": "^6.1.0",
    "theme-ui": "^0.3.1"
  },
  "devDependencies": {
    "prettier": "^2.0.5"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}

```

**Comment by mtully** [comment] 2020-08-23 19:28
@gvocale I was having a similar issue, but was able to resolve by running `yarn upgrade`.

**Comment by gvocale** [comment] 2020-08-24 03:27
Nice! that seemed to have worked for me too!

**Comment by kuworking** [comment] 2020-08-28 11:20
For me it has happened the same

- `props.theme` was empty (yet a `console.log` placed in `gatsby-plugin-theme-ui/index.js` worked)
- after a `yarn upgrade` it was full again

Since 2 hours ago I already run a `yarn upgrade` followed by various `yarns` I guess I'm facing the same behavior described by @gvocale 

```json
  "dependencies": {
    "@emotion/core": "10.0.35",
    "@emotion/styled": "10.0.27",
    "gatsby": "2.24.14",
    "gatsby-plugin-compile-es6-packages": "2.1.0",
    "gatsby-plugin-emotion": "4.3.10",
    "gatsby-plugin-netlify": "2.3.13",
    "gatsby-plugin-theme-ui": "0.3.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "theme-ui": "0.3.1"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "7.10.4",
    "babel-eslint": "10.1.0",
    "babel-plugin-emotion": "10.0.33"
  },
```

**Comment by lcdsmao** [comment] 2020-10-04 15:02
I also have this issue and `yarn upgrade` cannot solve this. 😢

```json
  "dependencies": {
    "gatsby": "^2.24.67",
    "gatsby-plugin-theme-ui": "^0.3.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "theme-ui": "^0.3.1"
  },
  "devDependencies": {
    "prettier": "2.1.2"
  },
```

**Comment by johngrasty** [comment] 2020-10-05 03:31
I seem to have this problem when @emotion/core is at 10.0.35, but it disappears on 10.0.28. I have not had time (nor probably in this case, the ability) to track down the root cause.

**Comment by lachlanjc** [comment] 2020-12-06 20:26
I suspect it’s an Emotion version mis-match—check your `yarn.lock` & make sure they’re all the same version. Additionally, you shouldn’t be installing `@emotion/core` manually—that may be the source of some of these issues. Closing as a discussion.

**Closed by lachlanjc** 2020-12-06 20:26 UTC
Labels: bug
