### ISSUE TITLE
Global jsx/sx pragma

### ISSUE THREAD

**Issue by alexluong** [system-ui/theme-ui#412] opened 2019-10-18 07:28 UTC
Hi. Is there anyway we can use `sx` prop without defining the custom pragma on the top of the files? Is there any drawback of using a babel plugin for that?

**Comment by epilande** [comment] 2019-10-18 14:45
Not sure if this is the recommended approach but this is how I build my components.

Create a base `Box` component or use the one from [reflexbox](https://github.com/rebassjs/rebass/tree/master/packages/reflexbox).

Here's an abstract example:
```js
import styled from '@emotion/styled'
import css from '@styled-system/css';

const sx = props => css(props.sx)(props.theme);

export const Box = styled('div')(sx)
```

Usage:
```jsx
```

Then have everything extend `Box`.

**Comment by jxnblk** [comment] 2019-10-18 16:09
@alexluong you can set up a custom babel config to automatically add the jsx pragma comment, but it will affect all files, which might or might not be what you want. See https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#pragma

@epilande this is essentially coming in #411

**Comment by alexluong** [comment] 2019-10-18 17:52
@jxnblk thank you, that is what I’m asking. Is there a situation where I don’t want it to affect all files? What is the downside?

**Comment by adamsoffer** [comment] 2019-10-23 10:26
@jxnblk I haven't been able to successfully get theme-ui to work with the custom babel config 

Check out the error below:
https://codesandbox.io/s/theme-ui-starter-4ydj0

Any idea what I'm doing wrong?

**Comment by jxnblk** [comment] 2019-10-23 14:22
@adamsoffer I don't see the `jsx` import in your codesandbox, did you forget to import that?

**Comment by adamsoffer** [comment] 2019-10-23 14:24
@jxnblk Even when I import jsx, the sx attributes still get ignored. The theme only is applied when a pragma is present.

**Comment by adamsoffer** [comment] 2019-10-23 14:34
Gotcha. How do I configure the babel plugin so that I don't have to add a pragma to every file?

**Comment by adamsoffer** [comment] 2019-10-26 16:58
@jxnblk I tried a few different configurations but no luck. Have you confirmed using this plugin works on your  end?

**Comment by lachlanjc** [comment] 2020-11-18 01:34
The mentioned issues/PRs I think cover this functionality for setting the JSX pragma & the Components have since been published/exported from the default package; @hasparus I’m cool with closing this issue

**Closed** 2020-11-18 12:57 UTC
