### ISSUE TITLE
Access nested colors?

### ISSUE THREAD

**Issue by loganpowell** [system-ui/theme-ui#250] opened 2019-07-30 00:17 UTC
I looked for a similar issue, but couldn't find one, realizing I may not know exactly how to ask this question, but here goes:

Is there a way to access nested colors defined in theme.js? E.g., if I have a theme like:

```js
initialColorMode: 'default',
  useCustomProperties: true,
  colors: {
    text: "#000",
    background: "#fff",
    base: {
       primary: "#..",
       secondary: "#.."
    },
    accent: { ... },
    modes: {
      saturated: {
         base: {
             primary: "#...",
             secondary: "#..."
         }, ...
    }
}
```
is there a way in the `sx` prop to refer to these nested values so that I can flip the colorMode switch and the nested values of the mode get chosen?

I've had no luck with:
```js
<div
      sx={{
        backgroundColor: 'base.primary',
      }}
    >
```
but using `useThemeUI` like:

```js
  const context = useThemeUI()
  const {
    theme
  } = context

// then...
   <div
      sx={{
        backgroundColor: theme.colors.base.primary,
        padding: '20px 0',
        width: '100%'
      }}
    >
```
works, but doesn't this marry the component to the default `colorMode`?

**Comment by loganpowell** [comment] 2019-07-30 00:20
edited typo above...

**Comment by jxnblk** [comment] 2019-07-30 19:27
The `useThemeUI` hook had a bug where the color mode was not reflected in `context.theme`, but that should have been fixed in #226 

Generally, the first approach with `backgroundColor: 'base.primary'` *should* work, but you might've found a bug. I'll look into this to see if I can reproduce it

**Comment by jxnblk** [comment] 2019-07-30 20:28
I've added tests in #254 – I can't reproduce the issues you're seeing, but if you have a reproduction that you can link to that'd be super helpful

**Comment by jxnblk** [comment] 2019-07-30 20:29
Oh! I bet this is related to #224 - will get some tests in place for that

**Comment by jxnblk** [comment] 2019-07-30 21:43
Closing as duplicate of #224

**Closed by jxnblk** 2019-07-30 21:43 UTC
