### ISSUE TITLE
gatsby-theme-ui-blog useThemeUI empty, useColorMode throws requires the ColorModeProvider

### ISSUE THREAD

**Issue by bogdansoare** [system-ui/theme-ui#971] opened 2020-06-01 14:38 UTC
**Describe the bug**
I'm using `gatsby-theme-ui-blog` theme. 
`theme`, `colorMode` and `setColorMode` from `useThemeUI` are null or undefined, and when using `useColorMode` throws requires the ColorModeProvider error

Although the providers seem to be present  
<img width="1530" alt="Screenshot 2020-06-01 at 17 46 37" src="https://user-images.githubusercontent.com/2750170/83420861-e627af00-a42f-11ea-9419-1cf5a1c4879e.png">

**To Reproduce**
1. Install gatsby-theme-ui-blog and configure it in gatsby-config.js
2. Try to use `useThemeUI` or `useColorMode `

**Expected behavior**
To be able to use those hooks when using gatsby-theme-ui-blog.

**Additional context**
gatsby-theme-ui-blog@^0.3.1

**Comment by ehowey** [comment] 2020-06-04 03:47
@bogdansoare what gatsby version are you running into.  I am getting an odd error with `useThemeUI`.

Currently on gatsby v2.21.21 everything works.

I upgraded to gatsby v2.22.20 today and the following code returns null:

```jsx
  const { theme } = useThemeUI()
```

Try downgrading to an earlier Gatsby version and see if that fixes it for you.  Curious if this is a similar/same problem I am having.

**Comment by bogdansoare** [comment] 2020-06-04 07:31
@ehowey I'm running on gatsby version `2.22.15`, I downgraded to `2.21.21` and it worked like you mentioned.

**Comment by jxnblk** [comment] 2020-06-04 14:35
Thanks for reporting this! Unfortunately, I couldn't reproduce this locally, but I suspect, it *might* be related to mismatched React contexts -- could you provide the output from `yarn list` or `npm ls` to see if there are any mismatched versions or duplicate packages installed?

**Comment by bogdansoare** [comment] 2020-06-05 07:18
@jxnblk thanks for looking into this.
Unfortunately I can't share the list on github since it's too long, here is a [dropbox link](https://www.dropbox.com/s/ashlbj12b6c9b9f/yarn-list-output.txt?dl=0) with the result from `yarn list`

**Comment by ehowey** [comment] 2020-06-05 12:25
I was having a hell of a time with Yarn last night.  All sorts of weird stuff.  I tried my normal tricks of deleting node_modules, deleting yarn.lock, clearing yarns cache. I have had the mismatched React versions before and fixed it.

I was also having trouble with `@theme-ui/prism` not installing despite being in the lock file properly. This was isolated to yarn, worked fine with npm in my tests trying to solve the bug.

The good news is I tried to replicate these problems with the default Gatsby starter and couldn't do it. So I don't think what is happening is widespread and could be some kind of funky business on my end of things.

Eventually I had to remove some packages (specifically @theme-ui/prism) and re-add them and also pin Gatsby to an earlier version. For now that is working fine and I am going to leave it there for now until I have some more time.

I don't know the details of how npm works but it was very odd how yarn wouldn't install the package properly despite being in the lock file, almost like a file corruption on their end of things or something.  I have never seen something like it before - albeit I am not the worlds most experienced developer either.

**Comment by justinkuntz** [comment] 2020-06-05 14:26
I had similar issues on another Gatsby project (not using Theme-UI). I traced it to a package that had a conflict with my latest version of Node. I had to add a `.nvmrc` file that explicitly called for `v12.17.0`. Not sure if that will help but might be worth a shot.

**Comment by ehowey** [comment] 2020-06-07 05:25
So - I noticed something when pocking around. It looks like Gatsby Admin is using Theme-UI v0.4.0-alpha.x. This means there are overlapping installs of Theme-UI. I think this is what is causing the issue.

I fixed it by using the following resolutions, yours may need to be different:

```js
"resolutions": {
    "theme-ui": "0.3.1",
    "@theme-ui/color": "0.3.1",
    "@theme-ui/match-media": "0.3.1",
    "@theme-ui/preset-tailwind": "0.3.0",
    "@theme-ui/prism": "0.3.0",
    "gatsby-plugin-theme-ui": "0.3.0"
  },
```

**Comment by ehowey** [comment] 2020-06-14 01:59
This will be fixed by: https://github.com/gatsbyjs/gatsby/pull/24810

**Comment by jxnblk** [comment] 2020-06-26 14:25
@bogdansoare can you confirm if this is still an issue with the latest version of Gatsby? I suspect it might have been related to the PR mentioned above

**Comment by ehowey** [comment] 2020-06-26 15:57
It is fixed for me since the changes to gatsby-admin got merged in.

**Comment by jxnblk** [comment] 2020-06-30 18:40
Closing for now, but please reopen this issue if you're still noticing this issue on the latest version of Gatsby

**Closed by jxnblk** 2020-06-30 18:40 UTC

**Comment by alexliusq** [comment] 2020-12-11 07:24
Encountered the same issue when I added `theme-ui` to see for non-blog pages, had to use @ehowey 's resolution fix, because gatsby-theme-blog uses the alpha version.
```shell
yarn why theme-ui
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "theme-ui"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "theme-ui@0.3.4"
info Has been hoisted to "theme-ui"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "64KB"
info Disk size with unique dependencies: "1.19MB"
info Disk size with transitive dependencies: "16.99MB"
info Number of shared dependencies: 39
=> Found "gatsby-theme-blog#theme-ui@0.4.0-alpha.3"
info This module exists because "gatsby-theme-blog" depends on it.
info Disk size without dependencies: "312KB"
info Disk size with unique dependencies: "1.43MB"
info Disk size with transitive dependencies: "17.23MB"
info Number of shared dependencies: 39
=> Found "gatsby-theme-ui-preset#theme-ui@0.4.0-alpha.3"
info This module exists because "gatsby-theme-blog#gatsby-theme-ui-preset" depends on it.
info Disk size without dependencies: "312KB"
info Disk size with unique dependencies: "1.43MB"
info Disk size with transitive dependencies: "17.23MB"
info Number of shared dependencies: 39
```
