### ISSUE TITLE
Remove paragraph max width

### ISSUE THREAD

**Issue by joshuabaker** [system-ui/theme-ui#1548] opened 2021-03-05 17:37 UTC
Currently the `Paragraph` component imposes a max width. This isn’t an ideal default to have as it assumes paragraph text is always the same font size. In our scenario, we have a `large` variant and, in that instance, we want the text to span the full width.

https://github.com/system-ui/theme-ui/blob/4b4e8f5c24aec13ccf43d17c0cb2b00be616e871/packages/components/src/Paragraph.js#L18-L20

Because this is nested in a media query (not sure why) it’s a bit of a faff to remove.

Any thoughts on removing that?

**Comment by lachlanjc** [comment] 2021-03-05 20:25
Yep! I'd totally be in support of removing, I think it's much better-suited for the theme. I'm closing as a duplicate of #1476.

**Closed as completed by lachlanjc** 2021-03-05 20:25 UTC

**Comment by flo-sch** [comment] 2021-03-08 16:09
(Just to confirm, a PR is open)
