### ISSUE TITLE
Color modes not using CSS custom properties

### ISSUE THREAD

**Issue by okonet** [system-ui/theme-ui#1406] opened 2020-12-30 18:31 UTC
Looking at the code I see that to set the color mode, it relies on the emotion theme provider:

https://github.com/system-ui/theme-ui/blob/6d9e29369a76c2802a1bb8253efaef072a087fbc/packages/color-modes/src/index.tsx#L111-L117

This generates unnecessary class names in order to change the color even though all the custom props are in DOM:

<img width="854" alt="CleanShot 2020-12-30 at 19 29 59@2x" src="https://user-images.githubusercontent.com/11071/103373509-736dd780-4ad5-11eb-9a7e-d6d9548937e0.png">

I've build a quick experiment where I'm relying on changing only the className of the `body` element and it works as expected without any additional re-rendering caused by emotion.

I'm wondering if the current behavior is intentional and what's the motivation to rely on have JS runtime for changing color mode?

**Comment by atanasster** [comment] 2021-01-06 05:33
Hi @okonet - not sure i understand 100% the issue you are reporting, however if you mean that new emotion classes are generated because all the color references use a default value for css props - then this is changed in the latest beta versions.

what version are you using? Also if this is still an issue, can you please post an example to reproduce and help us fix it.

**Comment by lachlanjc** [comment] 2021-01-06 16:52
I'm also not really understanding the issue here. So we do generate all the custom properties in advance, explicitly so less JavaScript needs to run when the theme changes. But there's no way to build a reliable theme switcher without JavaScript: we're a React library, so we need JS to offer a hook for executing the switch from any UI or background component in your app, & there's not any decent way to switch body classes or switch all the custom properties used without JS. & since there's a hook for reading the current color mode, if we didn't run through JS, React wouldn't re-render with new data in that hook, so various parts of the app would be out of date.

Not requiring JS is a valid requirement for some apps/components, but Theme UI isn't the right library if you're looking for approaches close to the DOM.

**Comment by okonet** [comment] 2021-01-06 17:54
@atanasster hmm, let me try the latest beta. I'm on the latest stable version: 3.5.0 and this is still an issue. 

I do understand why you'd like to rely on the React context here, but I also am confused why is there the need to pre-render all CSS custom properties then. That's why I raised this question. To me having them in DOM should eliminate the need to rely on the context but it looks like I'm mistaken?

**Comment by lachlanjc** [comment] 2021-01-06 18:20
Ah, I see. I'm not sure the original idea, but my guess is it makes switching color modes faster: since the CSS has already been rendered & written to DOM & parsed by the browser, once the class name changes, the browser can immediately repaint the elements without waiting on all those steps to happen first. We prerender the `printColorModeName` custom properties as well so we're not relying on JavaScript hooks to do all the updates for print-optimized pages.

**Comment by atanasster** [comment] 2021-01-06 19:28
@okonet - got and i believe your issue would be fixed by #1327 - where the css custom variables are only updated on the body tag. This way the individual components styles should not change and emotion should not create new classes on color mode change.

we would really appreciate if you can try it out and let us know, i haven’t  specifically done the tests that you have

**Comment by okonet** [comment] 2021-01-06 19:36
@atanasster is it released already? Under which version?

**Comment by atanasster** [comment] 2021-01-06 19:56
> @atanasster is it released already? Under which version
Yes i see it was merged start of December. Can you try ‘ 0.6.0-alpha.4‘

**Comment by okonet** [comment] 2021-01-06 21:11
I'll try. Last time I tried I could not make it work with React 17 with mdx. Maybe I'll stay on 16.8

**Comment by atanasster** [comment] 2021-01-06 21:51
Interesting - i am using react 17 and mdxjs and latest beta works fine. Just keep in mind mdxjs does not support automatic runtime.

**Comment by okonet** [comment] 2021-01-07 15:01
> Just keep in mind mdxjs does not support automatic runtime.

Yeah exactly my problem, I don't know how to configure the whole thing. Instructions for emotion / nextjs aren't compatible with Theme UI.

Also there is https://github.com/system-ui/theme-ui/tree/develop/packages/mdx which don't have any documentation on how to use it so it's been quite frustrating experience migrating to React 17 so far.

**Comment by okonet** [comment] 2021-01-07 15:30
@atanasster just tried the latest beta and I still see the same behavior:

https://user-images.githubusercontent.com/11071/103910610-52286f00-5105-11eb-9a94-5f95b64e3515.mp4

**Comment by atanasster** [comment] 2021-01-07 18:11
Thanks a lot @okonet - do you know what style prop changes to force the re-create of the emotion classes? I thought it was only the (unnecessary) default value for the css custom variables that changes on color mode change.
i am on the road for another 2 weeks, but will also try to check when i have some time.

**Comment by okonet** [comment] 2021-01-07 18:43
> do you know what style prop changes to force the re-create of the emotion classes

Not really sure what you mean but all I do is this:

```js
setColorMode(colorModes[newTheme]);
```

in the theme selector...

**Comment by okonet** [comment] 2021-01-07 18:47
Here are the screenshots with two different themes:

<img width="1304" alt="CleanShot 2021-01-07 at 19 45 59@2x" src="https://user-images.githubusercontent.com/11071/103931746-18fdf800-5121-11eb-9790-a2fd3157e0f3.png">

<img width="1292" alt="CleanShot 2021-01-07 at 19 46 21@2x" src="https://user-images.githubusercontent.com/11071/103931762-1d2a1580-5121-11eb-8122-21d16b9c84f8.png">

**Comment by okonet** [comment] 2021-01-07 18:47
So from how it looks like it's still using default values that are changing between theme switches.

**Comment by okonet** [comment] 2021-01-07 18:55
Sorry I was on a wrong branch before but it looks like the issue is still there since I still see the default values on applied CSS:

<img width="1319" alt="CleanShot 2021-01-07 at 19 54 24@2x" src="https://user-images.githubusercontent.com/11071/103932479-2a93cf80-5122-11eb-9b4e-a908f00e3a58.png">

<img width="1335" alt="CleanShot 2021-01-07 at 19 54 07@2x" src="https://user-images.githubusercontent.com/11071/103932483-2e275680-5122-11eb-83a5-88cf84151675.png">

Not sure how to debug this yet... any pointers?

**Comment by okonet** [comment] 2021-01-07 18:59
I tried installing `0.6.0-alpha.2` but it's failing the build with some error coming from color resolution from theme so I cannot test it.

**Comment by atanasster** [comment] 2021-01-08 04:04
@okonet - it seems that you are indeed not updated to the latest (once you are, you shouldn't see anymore the default values for custom css vars). Can you share what is the exact error you see when you upgrade?

**Comment by okonet** [comment] 2021-01-08 09:27
I tried `0.6.0-beta.4` which worked for me but I still see the default values. What latest do you mean? I removed node_modules before to make sure I'm running the latest version. Maybe point me to a line I could setup debugger on to see what's going on?

**Comment by okonet** [comment] 2021-01-08 10:05
I'm looking at the compiled code that's installed with `0.6.0-beta.4` and it looks differently from your PR:

```javascript
var toVarValue = function toVarValue(key, value) {
  return "var(" + toVarName(key) + ", " + value + ")";
};
```

so it still has the `value` part for some reason.

<img width="446" alt="CleanShot 2021-01-08 at 11 04 52@2x" src="https://user-images.githubusercontent.com/11071/104002426-5ace8300-51a1-11eb-8c04-080a32d40e83.png">

**Comment by okonet** [comment] 2021-01-08 10:10
There is no way to install `0.6.0-alpha.2` it seems since the dependencies in root theme-ui package.json are defined with `^` so it always resolve internal `@theme-ui` packages to `alpha.4` for me 🤷 even though `theme-ui` is at `alpha.2`.

**Comment by okonet** [comment] 2021-01-08 10:12
Latest `develop` also has the default value code so it looks like your PR was reverted: 

https://github.com/system-ui/theme-ui/blob/5a2f4582977d0fc0b223776138d9692d0774cbc5/packages/color-modes/src/custom-properties.ts#L4-L5

**Comment by atanasster** [comment] 2021-01-08 14:32
Ouch, you are right - @hasparus - any idea what’s the situation?

**Comment by hasparus** [comment] 2021-01-08 14:32
> Latest develop also has the default value code so it looks like your PR was reverted:

https://github.com/system-ui/theme-ui/pull/1327#issuecomment-739725808

#1327 broke `@theme-ui/color`. I reverted it before `alpha.4`.

**Comment by hasparus** [comment] 2021-01-08 14:35
So, right now when you change the class on body it works as expected, but it won't (if I remember correctly) if you're using `@theme-ui/color`.

**Comment by atanasster** [comment] 2021-01-08 14:45
Sorry, I missed that, have no idea what did break in `@theme-ui/color`, if we get more details can try to fix it.

**Comment by hasparus** [comment] 2021-01-08 19:18
> Sorry, I missed that, have no idea what did break in @theme-ui/color, if we get more details can try to fix it.

https://github.com/system-ui/theme-ui/blob/6a7256ec8075e5a5c0f0a182a5554946ed8e2478/packages/color/src/index.ts#L8-L12

`getColor` reads these default values.

---

The implementation that would work is keeping raw values inside of theme object, but printing css properties when we build emotion style objects (in our `css` function)

**Comment by hasparus** [comment] 2021-01-08 19:41
@atanasster https://codesandbox.io/s/eloquent-franklin-2o8nx?file=/src/App.js

**Comment by atanasster** [comment] 2021-01-09 02:30
thanks @hasparus - got it, it's a bit hacky to parse back the original color as a string. 

I think we can fix it
1. add to the `theme.original.colors` the original values of colors (and potentially any other vars)
2. use the body variables (can be buggy though)
```
export const getColor = (theme: Theme, color: string) => {
  ...
  return isCustomProperty
    ? getComputedStyle(document.body).getPropertyValue(colorValue)
    : colorValue
}
```

**Comment by hasparus** [comment] 2021-01-10 23:52
> use the body variables (can be buggy though)

True. Breaks during SSR.

I like (1) a bit, but I think I'll nead to read https://github.com/system-ui/theme-ui/pull/259 and https://github.com/system-ui/theme-ui/pull/274 again.

**Comment by atanasster** [comment] 2021-01-11 00:25
> True. Breaks during SSR.

Not exactly sure, since `getColor` with custom css vars happens after first setting the custom vars to the body

In any case, parsing the string values of the css vars is quite dangerous and there aren't any tests to cover it. I hope to be back home next week and have some time and at the very least I will add regression tests for `getColor` with custom css variables in the theme.

**Comment by hasparus** [comment] 2021-01-14 10:48
> Not exactly sure, since getColor with custom css vars happens after first setting the custom vars to the body

I've been thinking that `document` is undefined.

**Comment by lachlanjc** [comment] 2022-10-06 00:06
I believe this issue is resolved now? But not 100% sure. @hasparus want to glance?

**Comment by hasparus** [comment] 2022-10-06 04:34
Right now, colors computed with `@theme-ui/color`, `polished` or any similar library don't create a new CSS Custom Property, so they need recomputation by context update, not just a simple swap of custom properties.

So — color mode changes will still need the context update unless we map all CSS properties that can use colors into a set of selectors one for each color mode, and I'm not quite sure that it's something we should do on our side or even desirable.

```css
body.mode-1 & { background-color: #111 }
body.mode-2 & { background-color: #222 }
body.mode-3 & { background-color: #333 }
```

We've improved the state of things a bit because of this issue, but I think we can close it and open a new one if we have an idea how to build a better color mode handling.

**Closed as completed by hasparus** 2022-10-06 04:34 UTC
Labels: enhancement
