### ISSUE TITLE
react fragment cannot use in mdx

### ISSUE THREAD

**Issue by toy-crane** [system-ui/theme-ui#1334] opened 2020-12-04 15:59 UTC
**Describe the bug**
i`m using typescript with theme UI
MDX seems to does not recognize react fragment <></>

**To Reproduce**
use fragment tag <></> in mdx component

**Expected behavior**
mdx return `@jsxFrag pragma is required when using an @jsx pragma with JSX fragments.ts(17017)`

**Screenshots**
<img width="872" alt="Screen Shot 2020-12-05 at 12 58 36 AM" src="https://user-images.githubusercontent.com/3426196/101185277-02cdc980-3695-11eb-884f-0d141d67cdb4.png">

**Additional context**
work around solution is that using `React.fragment`
is there another way to fix it?

**Comment by hasparus** [comment] 2020-12-04 21:20
This issue looks relevant https://github.com/mdx-js/mdx/pull/1014#issuecomment-732821243

**Comment by lachlanjc** [comment] 2022-01-29 16:46
<img width="1062" alt="Screen Shot 2022-01-29 at 11 45 24 AM" src="https://user-images.githubusercontent.com/5074763/151669434-ab0373ab-f859-47eb-a03c-fc1f2739fdcf.png">

I'm not able to reproduce this issue at this point, so closing for now. If you're still running into it, please fork my CodeSandbox with a repro: https://codesandbox.io/s/next-theme-ui-example-forked-gxcd0?file=/components/about.mdx

**Closed by lachlanjc** 2022-01-29 16:46 UTC
Labels: bug, help wanted, types
