### ISSUE TITLE
Gatsby v3 / Theme UI 0.6 - Not Hot Reloading

### ISSUE THREAD

**Issue by PaulieScanlon** [system-ui/theme-ui#1595] opened 2021-03-22 10:37 UTC
**Describe the bug**
When using Theme UI 0.6 and Gatsby v3 i'm noting that hot reloading doesn't update the styles when i save changes to the Theme UI styles. I'm using `gatsby-plugin-theme-ui` also v0.6. 

**To Reproduce**
Install: 
-  "gatsby": "^3.1.1",
-  "gatsby-plugin-theme-ui": "^0.6.0",
-  "theme-ui": "^0.6.0"

Create a default export in `src/gatsby-plugin-theme-ui/index.js` and add some colors. The styles are picked up by the Gatsby "site" but when changing values in the theme object the Gatsby site doesn't hot reload.

**Expected behavior**
The Gatsby site should hot related when values in the theme object are updated

**Additional context**
This might be a problem with Gatsby v3 not Theme UI so apologies in advance if that is the case.

**Comment by PaulieScanlon** [comment] 2021-03-22 10:53
Just ran a test with 
-  "gatsby": "^2.32.11",
-  "gatsby-plugin-theme-ui": "0.3.5",
- "theme-ui": "0.3.5"

and hot reloading doesn't work there either. Maybe this is a Chrome or a Mac thing 🤷‍♂️

**Comment by hasparus** [comment] 2021-03-22 11:29
Possibly related issues: 

- https://github.com/system-ui/theme-ui/issues/1440
- https://github.com/gatsbyjs/gatsby/pull/29752

**Comment by t2ca** [comment] 2021-03-22 16:55
I've had the same issue before updating to Theme UI 0.6.

**Comment by fcisio** [comment] 2021-03-23 22:19
Yes, duplicate of #1440
The first part of the issue is fixed with Gatsby v3, meaning that changes above the pages are now computed.

So what's remaining is the "Ignored an update to the unaccepted module" error (more on this in #1440)

**Comment by fcisio** [comment] 2021-03-23 22:40
** Update

On the latest versions of Gatsby v2, `FAST_REFRESH: false` can trigger a full page reload on theme changes.

On v3 the `FAST_REFRESH` option doesn't seem to exist anymore. So it won't refresh nor reload.

---

> Until there is a fix for this it's better to stay on Gatsby v2.

**Comment by lachlanjc** [comment] 2021-03-23 23:26
Closing as a duplicate, but would love any help on #1440!

**Closed as completed by lachlanjc** 2021-03-23 23:26 UTC
Labels: bug, help wanted
