### ISSUE TITLE
Issue with MDXRenderer

### ISSUE THREAD

**Issue by vojtaholik** [system-ui/theme-ui#127] opened 2019-06-26 15:03 UTC
Hey @johno, `theme-ui` is looking awesome!

I'm getting a following error [after importing](https://github.com/vojtaholik/mdx-theme-ui/commit/7fc2b52221af8670d1bc347e05277c264006156e) `MDXRenderer`:

```
Failed to compile

./node_modules/gatsby-mdx/context.js 11:2
Module parse failed: Unexpected token (11:2)
You may need an appropriate loader to handle this file type.
| 
| export const MDXScopeProvider = ({ __mdxScope, children }) => (
>   <GatsbyMDXScopeContext.Provider value={__mdxScope}>
|     {children}
|   </GatsbyMDXScopeContext.Provider>
```

Do you think it could be because of `ThemeProvider`? It works fine for mdx in `/pages`, but I'd like to render eg. articles which is when `MDXRenderer` would come handy.

[Example repo](https://github.com/vojtaholik/mdx-theme-ui) 

🙏

**Comment by johno** [comment] 2019-06-26 16:00
Thanks for the reproduction! I'll look into it sometime this week.

**Comment by vojtaholik** [comment] 2019-06-28 07:26
importing `MDXRenderer` from `gatsby-plugin-mdx` instead of `gatsby-mdx` fixed this for me. 🎉

**Comment by johno** [comment] 2019-06-28 14:49
Nice! Yeah, in your repo you can remove `gatsby-mdx` and use `gatsby-plugin-mdx`. It will be officially released soon anyway 😄. Going to go ahead and close this since it's working for you.

Thanks for opening up an issue! Let us know if you encounter anything else ❤️

**Closed by johno** 2019-06-28 14:49 UTC
Labels: bug
