### ISSUE TITLE
Syntax error: pragma and pragmaFrag cannot be set when runtime is automatic.

### ISSUE THREAD

**Issue by t2ca** [system-ui/theme-ui#1160] opened 2020-08-30 17:24 UTC
I started having this error since updating Gatsby to the most recent version and updating React to v17.

`Syntax error: pragma and pragmaFrag cannot be set when runtime is automatic.`

edit: The same issue now exists with the latest version of React `react@16.14.0`, right now the only fix is to go back to `react@16.13.1 `and `react-dom@16.13.1`

**Comment by dcastil** [comment] 2020-09-25 10:57
I think the necessary imports are `jsx` and `jsxs`, not `_jsx` and `_jsxs`. This would be a breaking change because the current `jsx` function exported from `theme-ui` wouldn't work with the new 2-arg calls.

**Comment by hasparus** [comment] 2020-09-25 11:14
> I think the necessary imports are jsx and jsxs, not _jsx and _jsxs. 

Correct.

**Comment by piducancore** [comment] 2020-10-15 17:37
I'm having this error too with a newly created gatsby site.

**Comment by testowenyoung** [comment] 2020-10-16 00:23
Same problem.

**Comment by iamskok** [comment] 2020-10-16 00:53
I'm also experiencing the same issue using `gatsby-plugin-theme-ui`.

**Comment by t2ca** [comment] 2020-10-16 01:32
> I'm also experiencing the same issue with `gatsby-plugin-theme-ui@0.4.0-rc.5` and `theme-ui@0.4.0-rc.5`. Which package introduced this bug? Is there any temporary fix?

I believe these issues are because of recent changes to React. I got it working with `gatsby-plugin-theme-ui@0.3.0` and `react@16.13.1` and `react-dom@16.13.1`

**Comment by iamskok** [comment] 2020-10-16 01:44
> > I'm also experiencing the same issue with `gatsby-plugin-theme-ui@0.4.0-rc.5` and `theme-ui@0.4.0-rc.5`. Which package introduced this bug? Is there any temporary fix?
> 
> I believe these issues are because of recent changes to React. I got it working with `gatsby-plugin-theme-ui@0.3.0` and `react@16.13.1` and `react-dom@16.13.1`

What `gatsby` version are you on?

**Comment by t2ca** [comment] 2020-10-16 01:46
> > > I'm also experiencing the same issue with `gatsby-plugin-theme-ui@0.4.0-rc.5` and `theme-ui@0.4.0-rc.5`. Which package introduced this bug? Is there any temporary fix?
> > 
> > 
> > I believe these issues are because of recent changes to React. I got it working with `gatsby-plugin-theme-ui@0.3.0` and `react@16.13.1` and `react-dom@16.13.1`
> 
> What `gatsby` version are you on?

Most recent version, `gatsby@2.24.78`

**Comment by fatihyildizhan** [comment] 2020-10-16 07:06
I have the same problem. Here is my dependencies:

```
"dependencies": {
    "@rocketseat/gatsby-theme-docs": "^2.2.3",
    "gatsby": "^2.24.78",
    "gatsby-plugin-canonical-urls": "^2.3.13",
    "gatsby-plugin-google-analytics": "^2.3.18",
    "gatsby-plugin-manifest": "^2.4.34",
    "gatsby-plugin-offline": "^3.2.32",
    "gatsby-plugin-sitemap": "^2.4.17",
    "prop-types": "^15.7.2",
    "react": "^16.14.0",
    "react-dom": "^16.14.0"
  }
```

**Comment by hasparus** [comment] 2020-10-16 20:59
Waiting for https://github.com/emotion-js/emotion/pull/1970 or alternative work in Emotion.

**Comment by dcastil** [comment] 2020-10-23 19:11
Just adding here in case anyone sees this error message after upgrading a project to create-react-app v4:

Theme UI currently only supports the classic JSX runtime. Until emotion is upgraded to support the automatic runtime and Theme UI can be upgraded, add the comment `/** @jsxRuntime classic */` to all files using the `sx` prop. This should fix the issue.

```js
/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from 'theme-ui';
```

**Comment by sudarshan070** [comment] 2020-10-27 05:02
same problem
pragma and pragmaFrag cannot be set when runtime is automatic.

**Comment by hasparus** [comment] 2020-10-27 16:40
@sudarshan070 You need to use classic runtime. Take a look at dcastil's post.

**Comment by alex83130** [comment] 2020-11-03 22:24
Seems like Emotion was upgraded in order to support new JSX Runtime : https://github.com/emotion-js/emotion/blob/master/packages/core/CHANGELOG.md
Just need waiting Theme-UI upgrade now

**Comment by dcastil** [comment] 2020-11-04 14:26
I think there are still some issues in `@emotion/core` v10.1.1 which I wrote down in https://github.com/emotion-js/emotion/issues/2071#issuecomment-721760086. The functions for the automatic runtime are missing in the package and the functions for the classic runtime are used instead.

I didn't test it myself but I'm wondering why no one reported an issue yet. Maybe I'm missing something. 🤔

**Comment by hasparus** [comment] 2020-11-05 13:20
https://github.com/system-ui/theme-ui/pull/1237 will close this.

**Comment by dcastil** [comment] 2020-11-05 15:18
I marked that #1237 will close this. However, I'm not sure whether that's the best approach. pragma and pragmaFrag will never work in the automatic JSX runtime, that's intended behaviour.

**Comment by hasparus** [comment] 2020-11-05 15:33
> pragma and pragmaFrag will never work in the automatic JSX runtime, that's intended behaviour.

I never interpreted the title of this issue as "please make pragmaFrag work in automatic runtime", but I think you're right.
We also need to update the docs to educate about classic and automatic runtime, and change `/* @jsx jsx */` occurences in there to `@jsxImportSource`, as automatic runtime became the default.

**Closed** 2020-11-25 21:41 UTC

**Comment by JosephThomasVasquez** [comment] 2021-02-26 18:37
> Just adding here in case anyone sees this error message after upgrading a project to create-react-app v4:
> 
> Theme UI currently only supports the classic JSX runtime. Until emotion is upgraded to support the automatic runtime and Theme UI can be upgraded, add the comment `/** @jsxRuntime classic */` to all files using the `sx` prop. This should fix the issue.
> 
> ```js
> /** @jsxRuntime classic */
> /** @jsx jsx */
> import { jsx } from 'theme-ui';
> ```
> 
> You can also disable the automatic runtime globally instead by setting the environment variable `DISABLE_NEW_JSX_TRANSFORM=true`, e.g. [in your `.env` file](https://create-react-app.dev/docs/advanced-configuration).

Confirming it works with dependencies:
 ```
"@theme-ui/presets": "^0.3.5",
    "next": "^10.0.7",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "theme-ui": "^0.3.5"
```
