### ISSUE TITLE
8px margin on body from user agent stylesheet

### ISSUE THREAD

**Issue by camtheman256** [system-ui/theme-ui#1719] opened 2021-05-06 20:08 UTC
**Describe the bug**
When styles were applied to `<body>`, the default `margin: 0` prevented a margin being added to the body element. Now that styles are being applied to `<html>`, the default 8px margin that Chrome puts on the `<body>` element is showing up.

**To Reproduce**

1. Update to theme-ui 0.8 or above
2. Inspect body and find a margin: 8px applied by default to the `<body>` element

**Expected behavior**
Expected the `<body>` to have `margin: 0` as in prior versions of theme-ui

**Screenshots**
![image](https://user-images.githubusercontent.com/7855233/117359396-f71d4380-ae7c-11eb-98eb-c517ea12c231.png)

**Comment by hasparus** [comment] 2021-05-06 21:00
I totally missed it during testing. Thanks for the issue! This margin: 0 should definitely be applied to the body.

**Comment by hasparus** [comment] 2021-05-06 21:08
Deploying a fix after CI passes https://github.com/system-ui/theme-ui/commit/289ee1c7ddf84eee78e5cc3f1ec41e31a1c62835.

**Comment by lachlanjc** [comment] 2021-05-06 21:26
This is now released as [0.8.4](https://github.com/system-ui/theme-ui/releases/tag/v0.8.4)! Thanks @hasparus.

**Closed as completed by lachlanjc** 2021-05-06 21:26 UTC
Labels: bug

**Comment by CamilleHbp** [comment] 2022-05-19 06:06
Hello! Has there been a regression? I use `"@theme-ui/core": "^0.14.5"` (not using the complete `theme-ui` package since the `mdx` package causes problems with Vite build) and the body has the default 8px margin that Chrome puts on the <body> element. I'm using React v18 if this has any incidence. Everything else seems to be working perfectly.

Any tips on how to fix this? Thank you!
