### ISSUE TITLE
Export component themeKey

### ISSUE THREAD

**Issue by ericyip** [system-ui/theme-ui#858] opened 2020-04-20 07:11 UTC
**Is your feature request related to a problem? Please describe.**
I would like to get component's variant group and default variant name from component itself.

**Describe the solution you'd like**

It'd be great if theme-ui/components export its `themeKey` and `variant`
```jsx
 // Label.js
 const themeKey = 'forms'
 const variant = 'label'
 const Label = props => 
	<Box
		__themeKey={themeKey}
		variant={variant}
	/>

  Label.__themeKey = themeKey
  Label.variant = variant
  // or just a string
  Label.key = themeKey + '.' + variant

// on userland
import { Label, useThemeUI, get } from 'theme-ui'

const { theme } = useThemeUI
get(theme, Label.key)

```

I could create a pr for that :)

**Comment by jxnblk** [comment] 2020-04-21 19:45
I can see the rationale for picking up what theme key the component uses for its variants, but I think the default styles should be treated as private API. What's the need for accessing the default styles?

**Comment by ericyip** [comment] 2020-04-23 08:02
I see your point on treating default styles as private.
Let's just focus on the api of getting `themeKey`

**Comment by lachlanjc** [comment] 2020-12-03 00:54
Closing as a duplicate of the discussion in #1247

**Closed by lachlanjc** 2020-12-03 00:54 UTC
Labels: enhancement
